@startuml the-winner-is
participant Server
Actor me
participant App
activate App
App -> Lottery: LoadAttendees
activate Lottery
Lottery -> Requester: Ask for attentees
Requester -> EventBrite
EventBrite -> Requester
Requester -> Lottery: Attendees list
activate Lottery
loop remaining pages
Lottery -> Requester: Ask for attentees
Requester -> EventBrite
EventBrite -> Requester
Requester -> Lottery: Attendees list
end
Lottery -> Server: Push(winner)
deactivate Lottery

deactivate App
participant Lottery
participant Requester
participant EventBrite
me -> Server: Ask for winner(n)
Server -> Lottery: Ask next winner(n)
Server -> me

deactivate Lottery

@enduml